import {
  BACKEND_RPC_METHOD_CONTRACT_BY_METHOD,
  type BackendRpcClientMethodCatalogEntry,
} from '../../../packages/contracts/src/backend-rpc';

export const SRS_BACKEND_CLIENT_METHOD_CATALOG = [
  { clientMethod: 'systemHealth', rpcMethod: 'system.health' },
  { clientMethod: 'loadDatabase', rpcMethod: 'db.load' },
  { clientMethod: 'persistDatabase', rpcMethod: 'db.persist' },
  { clientMethod: 'diagnosticsStatus', rpcMethod: 'diagnostics.status' },
  { clientMethod: 'domainSyncStatus', rpcMethod: 'domainSync.status' },
  { clientMethod: 'domainSyncRepairPreview', rpcMethod: 'domainSync.repair.preview' },
  { clientMethod: 'domainSyncRepairApply', rpcMethod: 'domainSync.repair.apply' },
  { clientMethod: 'domainSyncConflictSourcesCleanup', rpcMethod: 'domainSync.conflictSources.cleanup' },
  { clientMethod: 'domainSyncConflictSourceCleanupCandidates', rpcMethod: 'domainSync.conflictSources.cleanupCandidates' },
  { clientMethod: 'browserDeckPage', rpcMethod: 'browser.deck.page' },
  { clientMethod: 'browserDeckMatchedIds', rpcMethod: 'browser.deck.matchedIds' },
  { clientMethod: 'browserDeckRowsByIds', rpcMethod: 'browser.deck.rowsByIds' },
  { clientMethod: 'browserDeckDocumentCounts', rpcMethod: 'browser.deck.documentCounts' },
  { clientMethod: 'browserStats', rpcMethod: 'browser.stats' },
  { clientMethod: 'browserCountCards', rpcMethod: 'browser.count' },
  { clientMethod: 'browserSourceExistenceRefreshCandidates', rpcMethod: 'browser.sourceExistence.refreshCandidates' },
  { clientMethod: 'browserSourceExistenceUpdate', rpcMethod: 'browser.sourceExistence.update' },
  { clientMethod: 'browserSourceExistenceByBlockIds', rpcMethod: 'browser.sourceExistence.byBlockIds' },
  { clientMethod: 'browserSourceExistenceSummary', rpcMethod: 'browser.sourceExistence.summary' },
  { clientMethod: 'browserSourceExistenceApplySweep', rpcMethod: 'browser.sourceExistence.applySweep' },
  { clientMethod: 'browserSourceExistenceApplySweepHost', rpcMethod: 'browser.sourceExistence.applySweepHost' },
  { clientMethod: 'reviewFeedback', rpcMethod: 'review.feedback' },
  { clientMethod: 'reviewTruthFlush', rpcMethod: 'review.truth.flush' },
  { clientMethod: 'reviewTruthBackfill', rpcMethod: 'review.truth.backfill' },
  { clientMethod: 'mergeSyncConflicts', rpcMethod: 'sync.conflict.merge' },
  { clientMethod: 'auditReviewSyncDivergence', rpcMethod: 'sync.reviewDivergence.audit' },
  { clientMethod: 'summarizeSyncConflicts', rpcMethod: 'sync.conflict.summarize' },
  { clientMethod: 'reloadSyncConflictDatabase', rpcMethod: 'sync.conflict.reload' },
  { clientMethod: 'queueProjectionSnapshot', rpcMethod: 'queue.projection.snapshot' },
  { clientMethod: 'queueProjectionRowsByIds', rpcMethod: 'queue.projection.rowsByIds' },
  { clientMethod: 'queueProjectionReplace', rpcMethod: 'queue.projection.replace' },
  { clientMethod: 'storageProjectionRebuild', rpcMethod: 'storage.projection.rebuild' },
  { clientMethod: 'neuralRoamAdvance', rpcMethod: 'neural-roam.advance' },
  { clientMethod: 'neuralRoamViewState', rpcMethod: 'neural-roam.viewState' },
  { clientMethod: 'neuralRoamCommand', rpcMethod: 'neural-roam.command' },
  { clientMethod: 'privateHealth', rpcMethod: 'private.health' },
  { clientMethod: 'privateDiagnosticsStatus', rpcMethod: 'private.diagnostics.status' },
  { clientMethod: 'privateAuditQuery', rpcMethod: 'private.audit.query' },
  { clientMethod: 'privateRead', rpcMethod: 'private.read.cards' },
  { clientMethod: 'privateRead', rpcMethod: 'private.read.queues' },
  { clientMethod: 'privateRead', rpcMethod: 'private.read.sessions' },
  { clientMethod: 'privateCommand', rpcMethod: 'private.command.execute' },
  { clientMethod: 'submitHotspotCommand', rpcMethod: 'hotspot.command.submit' },
  { clientMethod: 'getHotspotJob', rpcMethod: 'hotspot.job.get' },
  { clientMethod: 'executeXiuyuanSync', rpcMethod: 'xiuyuan.sync.execute' },
  { clientMethod: 'executeProgressiveCommand', rpcMethod: 'progressive.command.execute' },
  { clientMethod: 'executeTopicDerivedCommand', rpcMethod: 'topic-derived.command.execute' },
  { clientMethod: 'executeReviewRiffFeedback', rpcMethod: 'review.riffFeedback.execute' },
  { clientMethod: 'executeReviewSourceRefresh', rpcMethod: 'review.sourceRefresh.execute' },
  { clientMethod: 'browserAggregateSnapshot', rpcMethod: 'browser.aggregate.snapshot' },
  { clientMethod: 'browserAggregatePage', rpcMethod: 'browser.aggregate.page' },
  { clientMethod: 'browserAggregateFocus', rpcMethod: 'browser.aggregate.focus' },
  { clientMethod: 'graphQuery', rpcMethod: 'graph.query' },
  { clientMethod: 'semanticCommand', rpcMethod: 'semantic.command.execute' },
  { clientMethod: 'semanticSessionRead', rpcMethod: 'semantic.session.read' },
  { clientMethod: 'semanticSidebarRead', rpcMethod: 'semantic.sidebar.read' },
  { clientMethod: 'semanticBrowserRead', rpcMethod: 'semantic.browser.read' },
  { clientMethod: 'p6OwnershipQuery', rpcMethod: 'p6.ownership.query' },
  { clientMethod: 'p6OwnershipCommand', rpcMethod: 'p6.ownership.command' },
  { clientMethod: 'ingestKernelTransactions', rpcMethod: 'kernel.transaction.ingest' },
  { clientMethod: 'dequeueKernelTransactions', rpcMethod: 'kernel.transaction.dequeue' },
  { clientMethod: 'requeueKernelTransactions', rpcMethod: 'kernel.transaction.requeue' },
  { clientMethod: 'resolveAutoCardDecision', rpcMethod: 'autocard.decision.resolve' },
  { clientMethod: 'executeAutoCard', rpcMethod: 'autocard.execute' },
].map((entry) => ({
  ...entry,
  family: BACKEND_RPC_METHOD_CONTRACT_BY_METHOD[entry.rpcMethod].family,
  exposure: 'facade',
})) as readonly BackendRpcClientMethodCatalogEntry[];
